#!/bin/bash
# Installs host-side DSI-wiki-* CLI wrappers for the Docker deployment path
# (SERVICES/DEPLOY.md). Unlike setup.sh's native/systemd path -- which installs real
# ~/.local/bin/DSI-wiki-* wrappers that call SKILLS/cli/*.py directly -- a Docker
# deployment's SKILLS/cli/*.py only exist inside the running containers, so these
# wrappers proxy each call through `docker compose exec` instead.
#
# Usage: bash TOOLS/install-cli-proxies.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/SERVICES/docker-compose.yml"
ENV_FILE="$REPO_ROOT/SERVICES/.env"
BIN_DIR="$HOME/.local/bin"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "error: $COMPOSE_FILE not found -- run this from a cloned DSI-Wiki repo." >&2
    exit 1
fi

mkdir -p "$BIN_DIR"

# Reads: gateway's WIKI_BASE_DIR mount is :ro (see docker-compose.yml) -- fine for
# list/get/search/scan.
write_read_proxy() {
    local name="$1" script="$2"
    cat > "$BIN_DIR/$name" <<EOF
#!/bin/bash
# Generated by TOOLS/install-cli-proxies.sh -- do not edit by hand, re-run the
# installer instead. Proxies into the gateway container (read-only mount).
set -euo pipefail
exec docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" exec -T gateway \\
    python3 SKILLS/cli/$script "\$@"
EOF
    chmod +x "$BIN_DIR/$name"
}

# Writes: gateway's mount is read-only, must go through ingest instead (rw mount).
write_write_proxy() {
    local name="$1" verb="$2" argc="$3" usage="$4"
    cat > "$BIN_DIR/$name" <<EOF
#!/bin/bash
# Generated by TOOLS/install-cli-proxies.sh -- do not edit by hand, re-run the
# installer instead. Proxies into the ingest container (read-write mount) --
# gateway's WIKI_BASE_DIR mount is read-only, a write needs ingest.
set -euo pipefail
if [ "\$#" -ne $argc ]; then
    echo "usage: $usage" >&2
    exit 1
fi
exec docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" exec -T ingest \\
    python3 SKILLS/cli/topic_ops.py $verb "\$@"
EOF
    chmod +x "$BIN_DIR/$name"
}

# Not proxied through docker exec -- reads a plain host file (DSI-BEHOLDER's status snapshot,
# written by its own watchdog loop, native process, no container involved), so there's nothing
# to reach inside a container for. No network round-trip either way -- see wiki_stat.py.
write_host_native_proxy() {
    local name="$1" script="$2"
    cat > "$BIN_DIR/$name" <<EOF
#!/bin/bash
# Generated by TOOLS/install-cli-proxies.sh -- do not edit by hand, re-run the
# installer instead. Runs directly on the host, not proxied into any container.
set -euo pipefail
exec python3 "$REPO_ROOT/SKILLS/cli/$script" "\$@"
EOF
    chmod +x "$BIN_DIR/$name"
}

write_read_proxy  DSI-wiki-topics        wiki_topics.py
write_read_proxy  DSI-wiki-get           wiki_get.py
write_read_proxy  DSI-wiki-search        wiki_search.py
write_read_proxy  DSI-wiki-internal-scan internal_scan.py
write_read_proxy  DSI-wiki-obsidian-link wiki_obsidian_link.py
write_read_proxy  DSI-wiki-provenance    provenance.py
write_write_proxy DSI-wiki-rename rename_topic 2 "DSI-wiki-rename <old-topic> <new-topic>"
write_write_proxy DSI-wiki-delete delete_topic 1 "DSI-wiki-delete <topic>"
write_host_native_proxy DSI-wiki-stat wiki_stat.py

if ! grep -q '.local/bin' "$HOME/.bashrc" 2>/dev/null; then
    printf '\n# added by DSI-Wiki TOOLS/install-cli-proxies.sh\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$HOME/.bashrc"
    echo "Added ~/.local/bin to PATH in ~/.bashrc (open a new shell, or: source ~/.bashrc)"
fi

echo "Installed: DSI-wiki-topics, DSI-wiki-get, DSI-wiki-search, DSI-wiki-internal-scan, DSI-wiki-obsidian-link, DSI-wiki-provenance, DSI-wiki-rename, DSI-wiki-delete, DSI-wiki-stat -> $BIN_DIR"
